include_defs('//ros/rosdistro/DEFS')

genrule(
  name = 'ros',
  srcs = rosdistro_tarballs + [
    '//deps/console_bridge:console_bridge',
  ],
  cmd = 'unzip "$SRCDIR/*.zip" \
         && catkin config \
            --init \
            --mkdirs \
            --source-space . \
            --isolate-devel \
            --install \
            --install-space $OUT \
            --merge-install \
         && catkin build \
         && ls $OUT',
  out = 'install',
)